### ISSUE TITLE
error when loading on my spigot 1.15 server...

### ISSUE THREAD

**Issue by amsedal** [Raffa50/Spigot-ExpBook#1]
[05:47:54] [Server thread/ERROR]: Could not load 'plugins/ExpBook.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: aldrigos/mc/expbook/ExpBookPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigotmc-1.15.jar:git-Spigot-f39a89e-4633e6c]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[spigotmc-1.15.jar:git-Spigot-f39a89e-4633e6c]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:253) [spigotmc-1.15.jar:git-Spigot-f39a89e-4633e6c]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:351) [spigotmc-1.15.jar:git-Spigot-f39a89e-4633e6c]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:202) [spigotmc-1.15.jar:git-Spigot-f39a89e-4633e6c]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:783) [spigotmc-1.15.jar:git-Spigot-f39a89e-4633e6c]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.UnsupportedClassVersionError: aldrigos/mc/expbook/ExpBookPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_242]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:757) ~[?:1.8.0_242]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_242]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:131) ~[spigotmc-1.15.jar:git-Spigot-f39a89e-4633e6c]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigotmc-1.15.jar:git-Spigot-f39a89e-4633e6c]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_242]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_242]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59) ~[spigotmc-1.15.jar:git-Spigot-f39a89e-4633e6c]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigotmc-1.15.jar:git-Spigot-f39a89e-4633e6c]
        ... 6 more

**Comment by Raffa50** [comment]
You need Java11+
download latest Java: https://www.oracle.com/java/technologies/javase-jdk14-downloads.html
